name: Publish packages

on:
  release:
    types: [published]

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 9.2.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          scope: "@mauroerta"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Build packages
        run: pnpm build

      - name: Publish packages
        run: pnpm publish --access public --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
